import type { Metadata } from 'next';
import './globals.css';
import { Toaster } from '@/components/ui/sonner';
import { Nunito } from 'next/font/google';
import Loading from './loading';
import { Suspense } from 'react';
import Providers from './providers';

const nunito = Nunito({
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Quickinit Next',
	description: 'Generated by create qi',
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`antialiased ${nunito.className}`}>
				<Suspense fallback={<Loading />}>
					<Providers>
						<Toaster duration={2500} richColors closeButton position='top-right' />
						{children}
					</Providers>
				</Suspense>
			</body>
		</html>
	);
}
